-- ==========================================
-- MIGRACION DE COMPATIBILIDAD Y PERMISOS
-- ==========================================
BEGIN;

-- ==========================================
-- EMAIL HISTORICO OPCIONAL
-- ==========================================
-- Conserva los correos existentes, pero ya no obliga a capturarlos en Usuarios.
ALTER TABLE usuarios ALTER COLUMN email DROP NOT NULL;

-- ==========================================
-- ESTRUCTURA DE MODULOS
-- ==========================================
CREATE TABLE IF NOT EXISTS modulos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    codigo VARCHAR(50) NOT NULL UNIQUE,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS usuario_modulos (
    usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    modulo_id INTEGER NOT NULL REFERENCES modulos(id) ON DELETE CASCADE,
    PRIMARY KEY (usuario_id, modulo_id)
);

-- ==========================================
-- CATALOGO INICIAL
-- ==========================================
INSERT INTO modulos (nombre, codigo)
VALUES
    ('Clientes', 'clientes'),
    ('Servicios', 'servicios'),
    ('Planes', 'planes'),
    ('Cotización / Proformas', 'cotizaciones'),
    ('Pagos', 'pagos'),
    ('Caja', 'caja'),
    ('Proveedores', 'proveedores'),
    ('Tickets', 'tickets'),
    ('Reportes', 'reportes')
ON CONFLICT (codigo) DO NOTHING;

-- ==========================================
-- PERMISOS INICIALES DE CUENTAS EXISTENTES
-- ==========================================
-- Las cuentas existentes conservan su acceso y quedan listas para administrar permisos.
INSERT INTO usuario_modulos (usuario_id, modulo_id)
SELECT usuarios.id, modulos.id
FROM usuarios
CROSS JOIN modulos
ON CONFLICT (usuario_id, modulo_id) DO NOTHING;

COMMIT;
