-- ==========================================
-- PLANES ESTANDAR Y PERSONALIZADOS
-- ==========================================
BEGIN;

CREATE TABLE IF NOT EXISTS planes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    velocidad VARCHAR(30) NOT NULL,
    precio_mensual NUMERIC(10, 2) NOT NULL,
    tipo_plan VARCHAR(20) NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'Activo',
    descripcion TEXT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_planes_nombre UNIQUE (nombre),
    CONSTRAINT ck_planes_tipo_plan CHECK (tipo_plan IN ('ESTANDAR', 'PERSONALIZADO')),
    CONSTRAINT ck_planes_precio_positivo CHECK (precio_mensual > 0),
    CONSTRAINT ck_planes_estado CHECK (estado IN ('Activo', 'Inactivo'))
);

COMMIT;
