-- ==========================================
-- MIGRACION DE GESTION DE CLIENTES
-- ==========================================
BEGIN;

-- ==========================================
-- CATALOGOS GEOGRAFICOS
-- ==========================================
-- Los codigos se dejan NULL porque aun no existe un catalogo oficial definido.
CREATE TABLE IF NOT EXISTS departamentos (
    id_departamento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    codigo VARCHAR(20) NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'Activo',
    CONSTRAINT uq_departamentos_nombre UNIQUE (nombre),
    CONSTRAINT ck_departamentos_estado CHECK (estado IN ('Activo', 'Inactivo'))
);

CREATE TABLE IF NOT EXISTS municipios (
    id_municipio INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_departamento INTEGER NOT NULL REFERENCES departamentos(id_departamento),
    nombre VARCHAR(100) NOT NULL,
    codigo_postal VARCHAR(10) NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'Activo',
    CONSTRAINT uq_municipios_departamento_nombre UNIQUE (id_departamento, nombre),
    CONSTRAINT ck_municipios_estado CHECK (estado IN ('Activo', 'Inactivo'))
);

-- ==========================================
-- CLIENTES
-- ==========================================
CREATE TABLE IF NOT EXISTS clientes (
    id_cliente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_municipio INTEGER NOT NULL REFERENCES municipios(id_municipio),
    codigo VARCHAR(50) NOT NULL UNIQUE,
    nombres VARCHAR(150) NOT NULL,
    apellidos VARCHAR(150) NOT NULL,
    dpi VARCHAR(30) NULL,
    telefono_principal VARCHAR(30) NOT NULL,
    correo VARCHAR(254) NULL,
    direccion VARCHAR(300) NOT NULL,
    referencia VARCHAR(300) NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'Activo',
    CONSTRAINT ck_clientes_estado CHECK (estado IN ('Activo', 'Inactivo'))
);

-- ==========================================
-- SEMILLA DE SOLOLÁ
-- ==========================================
-- No se inventan codigo ni codigo_postal: ambos quedan NULL hasta contar con una
-- fuente oficial. Las condiciones NOT EXISTS hacen segura la ejecucion repetida.
INSERT INTO departamentos (nombre, codigo, estado)
SELECT 'Sololá', NULL, 'Activo'
WHERE NOT EXISTS (
    SELECT 1
    FROM departamentos
    WHERE nombre = 'Sololá'
);

INSERT INTO municipios (id_departamento, nombre, codigo_postal, estado)
SELECT departamento.id_departamento, municipios.nombre, NULL, 'Activo'
FROM departamentos AS departamento
CROSS JOIN (
    VALUES
        ('Sololá'),
        ('San José Chacayá'),
        ('Santa María Visitación'),
        ('Santa Lucía Utatlán'),
        ('Nahualá'),
        ('Santa Catarina Ixtahuacán'),
        ('Santa Clara La Laguna'),
        ('Concepción'),
        ('San Andrés Semetabaj'),
        ('Panajachel'),
        ('Santa Catarina Palopó'),
        ('San Antonio Palopó'),
        ('San Lucas Tolimán'),
        ('Santa Cruz La Laguna'),
        ('San Pablo La Laguna'),
        ('San Marcos La Laguna'),
        ('San Juan La Laguna'),
        ('San Pedro La Laguna'),
        ('Santiago Atitlán')
) AS municipios(nombre)
WHERE departamento.nombre = 'Sololá'
  AND NOT EXISTS (
      SELECT 1
      FROM municipios AS existente
      WHERE existente.id_departamento = departamento.id_departamento
        AND existente.nombre = municipios.nombre
  );

COMMIT;
