-- ==========================================
-- MIGRACION DEL MODULO DE EMPLEADOS
-- ==========================================
BEGIN;

-- ==========================================
-- CATALOGO DE PUESTOS
-- ==========================================
CREATE TABLE IF NOT EXISTS puestos_empleado (
    id_puesto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'Activo',
    CONSTRAINT uq_puestos_empleado_nombre UNIQUE (nombre),
    CONSTRAINT ck_puestos_empleado_estado CHECK (estado IN ('Activo', 'Inactivo'))
);

INSERT INTO puestos_empleado (nombre, descripcion, estado)
VALUES
    ('Administrador', NULL, 'Activo'),
    ('Técnico', NULL, 'Activo'),
    ('Atención al cliente', NULL, 'Activo')
ON CONFLICT (nombre) DO NOTHING;

-- ==========================================
-- EMPLEADOS
-- ==========================================
CREATE TABLE IF NOT EXISTS empleados (
    id_empleado INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_puesto INTEGER NOT NULL REFERENCES puestos_empleado(id_puesto),
    id_municipio INTEGER NOT NULL REFERENCES municipios(id_municipio),
    codigo VARCHAR(50) NOT NULL,
    nombres VARCHAR(150) NOT NULL,
    apellidos VARCHAR(150) NOT NULL,
    tipo_documento VARCHAR(30) NOT NULL,
    numero_documento VARCHAR(30) NOT NULL,
    telefono_principal VARCHAR(30) NOT NULL,
    telefono_alternativo VARCHAR(30) NULL,
    correo VARCHAR(254) NULL,
    direccion VARCHAR(300) NOT NULL,
    fecha_ingreso DATE NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'Activo',
    observaciones TEXT NULL,
    foto_perfil VARCHAR(500) NULL,
    CONSTRAINT uq_empleados_codigo UNIQUE (codigo),
    CONSTRAINT uq_empleados_numero_documento UNIQUE (numero_documento),
    CONSTRAINT ck_empleados_estado CHECK (estado IN ('Activo', 'Inactivo'))
);

COMMIT;
