-- ==========================================
-- MIGRACION DEL MODULO DE INSTALACIONES
-- ==========================================
BEGIN;

-- ==========================================
-- INSTALACIONES
-- ==========================================
CREATE TABLE IF NOT EXISTS instalaciones (
    id_instalacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente INTEGER NOT NULL REFERENCES clientes(id_cliente),
    id_empleado INTEGER NOT NULL REFERENCES empleados(id_empleado),
    fecha_programada DATE NOT NULL,
    hora_programada TIME NOT NULL,
    observaciones TEXT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'Programada',
    observaciones_tecnicas TEXT NULL,
    fecha_finalizacion TIMESTAMP NULL,
    CONSTRAINT ck_instalaciones_estado CHECK (
        estado IN ('Programada', 'En Proceso', 'Completada')
    )
);

COMMIT;
